---
title: "Allowing Variable Burnin"
description: |
author:
  - name: Jacob Simmering, PhD 
    url: https://jacobsimmering.com
    affiliation: University of Iowa
    affiliation_url: https://uiowa.edu
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pkg-load}
library(tidyverse)
library(gtsummary)
library(survival)
library(patchwork)
```

```{r gen-outcomes}
if (Sys.info()["sysname"] == "Darwin") {
  root_dir <- "/Volumes/lss_jsimmeri_backup/data/tz-5ari-final"
} else {
  root_dir <- "/Shared/lss_jsimmeri_backup/data/tz-5ari-final"
}
model_data <- read_rds(glue::glue("{root_dir}/treated_model_data.rds"))

outcomes <- model_data %>%
  select(enrolid, drug, develops_pd, survival_time)
```

```{r}
cox_model <- function(outcomes, treatment, control, i) {
  matches <- read_rds(glue::glue("{root_dir}/matches/{treatment}_{control}_{i}.rds"))

  matched_data <- inner_join(outcomes, matches, by = "enrolid")

  model <- coxph(Surv(survival_time, develops_pd) ~ treatment,
                 data = matched_data,
                 cluster = pair_id,
                 robust = TRUE)

  results <- broom::tidy(model) %>%
    mutate(hr = exp(estimate),
           lb = exp(estimate - 1.96 * robust.se),
           ub = exp(estimate + 1.96 * robust.se),
           treatment = treatment,
           control = control, 
           burnin = i, 
           n_cases = nobs(model),
           n_people = nrow(matched_data),
           n_pairs = NROW(unique(matched_data$pair_id)),
           p.value = round(p.value, 4)) %>%
    select(treatment, control, burnin, n_cases, n_people, n_pairs, hr, lb, ub, p.value)

  return(results)
}

time_varying_cox_model <- function(outcomes, treatment, control, i) {
  matches <- read_rds(glue::glue("{root_dir}/matches/{treatment}_{control}_{i}.rds"))

  matched_data <- inner_join(outcomes, matches, by = "enrolid")

  model <- coxph(Surv(survival_time, develops_pd) ~ treatment,
                 data = matched_data,
                 cluster = pair_id,
                 robust = TRUE)

  tv_model <- cox.zph(model)
  step_fit <- survSplit(Surv(survival_time, develops_pd) ~ ., 
          data = matched_data,
          cut = seq(1, 10, 2) * 365,
          episode = "tgroup") %>%
    coxph(Surv(tstart, survival_time, develops_pd) ~ treatment:strata(tgroup),
          data = ., cluster = pair_id, robust = TRUE)

  step_model <- step_fit %>%
    broom::tidy() %>%
    mutate(
      period = stringr::str_extract(term, "=[0-9]*"),
      period = as.numeric(stringr::str_replace(period, "=", "")),
      period = period * 2 - 1
    )

  point <- model$coef[1]
  ci <- confint(model)
  lb <- ci[1]
  ub <- ci[2]

  p <- round(tv_model$table[1, 3], 4)

  print(glue::glue("{treatment} | {control} | {i} | SR cor = {p}"))
  d <- tibble(
      x = tv_model[1]$time,
      y = as.numeric(tv_model[1]$y),
      treatment = treatment,
      control = control, 
      i = i
    )

  write_rds(d, glue::glue("{root_dir}/fig_data/tbl_{treatment}_{control}_{i}.rds"))

  fig <- ggplot(d, aes(x = x / 365, y = exp(y))) +
    geom_smooth(method = "loess") + 
    geom_point(data = step_model,
               aes(x = period, y = exp(estimate))) + 
    geom_linerange(data = step_model,
                   aes(x = period, 
                       y = exp(estimate),
                       ymin = exp(estimate - 1.96 * robust.se),
                       ymax = exp(estimate + 1.96 * robust.se))) +
    geom_hline(yintercept = 1) + 
    geom_hline(yintercept = exp(point), linetype = 2) + 
    geom_hline(yintercept = exp(ub), linetype = 3) + 
    geom_hline(yintercept = exp(lb), linetype = 3) +
    theme_bw() + 
    scale_y_log10() + 
    labs(x = "Years of Follow-Up", y = "Hazard Ratio")
  write_rds(fig, glue::glue("{root_dir}/fig_data/{treatment}_{control}_{i}.rds"))

  return(tbl_regression(step_fit, exponentiate = TRUE))
}
```

```{r}
bind_rows(
  cox_model(outcomes, "tz", "tam", 0),
  cox_model(outcomes, "tz", "tam", 1),
  cox_model(outcomes, "tz", "tam", 2),
  cox_model(outcomes, "tz", "tam", 3),
  cox_model(outcomes, "tz", "tam", 4),
  cox_model(outcomes, "tz", "tam", 5),
  cox_model(outcomes, "tz", "5ari", 0),
  cox_model(outcomes, "tz", "5ari", 1),
  cox_model(outcomes, "tz", "5ari", 2),
  cox_model(outcomes, "tz", "5ari", 3),
  cox_model(outcomes, "tz", "5ari", 4),
  cox_model(outcomes, "tz", "5ari", 5),
  cox_model(outcomes, "tam", "5ari", 0),
  cox_model(outcomes, "tam", "5ari", 1),
  cox_model(outcomes, "tam", "5ari", 2),
  cox_model(outcomes, "tam", "5ari", 3),
  cox_model(outcomes, "tam", "5ari", 4),
  cox_model(outcomes, "tam", "5ari", 5)
)
```

```{r}
time_varying_cox_model(outcomes, "tz", "tam", 0)
time_varying_cox_model(outcomes, "tz", "tam", 1)
time_varying_cox_model(outcomes, "tz", "tam", 2)
time_varying_cox_model(outcomes, "tz", "tam", 3)
time_varying_cox_model(outcomes, "tz", "tam", 4)
time_varying_cox_model(outcomes, "tz", "tam", 5)
time_varying_cox_model(outcomes, "tz", "5ari", 0)
time_varying_cox_model(outcomes, "tz", "5ari", 1)
time_varying_cox_model(outcomes, "tz", "5ari", 2)
time_varying_cox_model(outcomes, "tz", "5ari", 3)
time_varying_cox_model(outcomes, "tz", "5ari", 4)
time_varying_cox_model(outcomes, "tz", "5ari", 5)
time_varying_cox_model(outcomes, "tam", "5ari", 0)
time_varying_cox_model(outcomes, "tam", "5ari", 1)
time_varying_cox_model(outcomes, "tam", "5ari", 2)
time_varying_cox_model(outcomes, "tam", "5ari", 3)
time_varying_cox_model(outcomes, "tam", "5ari", 4)
time_varying_cox_model(outcomes, "tam", "5ari", 5)
```

```{r}
tz_tam_fig <- read_rds(glue::glue("{root_dir}/fig_data/tz_tam_0.rds"))
tz_5ari_fig <- read_rds(glue::glue("{root_dir}/fig_data/tz_5ari_0.rds"))
tam_5ari_fig <- read_rds(glue::glue("{root_dir}/fig_data/tam_5ari_0.rds"))

bind_rows(
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_0.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_0.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_0.rds")),

  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_1.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_1.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_1.rds")),

  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_2.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_2.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_2.rds")),

  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_3.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_3.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_3.rds")),

  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_4.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_4.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_4.rds")),

  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_tam_5.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tz_5ari_5.rds")),
  read_rds(glue::glue("{root_dir}/fig_data/tbl_tam_5ari_5.rds")),
) %>%
  mutate(treatment = ifelse(treatment == "tz", "TZ/DZ/AZ", 
                            ifelse(treatment == "tam", "Tamsulosin", "5ARI")),
         control = ifelse(control == "tam", "Tamsulosin", "5ARI")) %>%
  mutate(comparison = paste(treatment, " vs ", control, sep = "")) %>%
  mutate(comparison = forcats::fct_relevel(comparison, "TZ/DZ/AZ vs Tamsulosin", "TZ/DZ/AZ vs 5ARI")) %>%
  mutate(i = glue::glue("Lead-In Duration\nof {i} Years")) %>%
  ggplot(aes(x = x / 365, y = y)) + 
  geom_smooth(method = "loess") + 
  facet_grid(rows = vars(i), cols = vars(comparison)) + 
  geom_hline(yintercept = 0) + 
  theme_bw() + 
  labs(x = "Years Since Medication Start", y = "Log Hazard Ratio")

ggsave("~/projects/pd-preprint/figure_sr-small-muliples.png", width = 8, height = 9.5)
```

As a way to summarize this, use GAMs to estimate the "improvement" over a null
model that assumes the HR is time invariant. 

```{r}
sr_test <- function(treatment, control, i) {
  d <- read_rds(glue::glue("{root_dir}/fig_data/tbl_{treatment}_{control}_{i}.rds"))

  results <- cor.test(d$x, d$y) %>%
    broom::tidy() %>%
    mutate(
      treatment = treatment,
      control = control, 
      i = i
    ) %>%
    select(treatment, control, i, estimate, conf.low, conf.high)

  return(results)
}

bind_rows(
  sr_test("tz", "tam", 0),
  sr_test("tz", "5ari", 0),
  sr_test("tam", "5ari", 0),

  sr_test("tz", "tam", 1),
  sr_test("tz", "5ari", 1),
  sr_test("tam", "5ari", 1),

  sr_test("tz", "tam", 2),
  sr_test("tz", "5ari", 2),
  sr_test("tam", "5ari", 2),

  sr_test("tz", "tam", 3),
  sr_test("tz", "5ari", 3),
  sr_test("tam", "5ari", 3),

  sr_test("tz", "tam", 4),
  sr_test("tz", "5ari", 4),
  sr_test("tam", "5ari", 4),

  sr_test("tz", "tam", 5),
  sr_test("tz", "5ari", 5),
  sr_test("tam", "5ari", 5)
) %>%
  mutate(treatment = ifelse(treatment == "tz", "TZ/DZ/AZ", 
                            ifelse(treatment == "tam", "Tamsulosin", "5ARI")),
         control = ifelse(control == "tam", "Tamsulosin", "5ARI")) %>%
  mutate(comparison = paste(treatment, "\nvs\n", control, sep = "")) %>%
  mutate(comparison = forcats::fct_relevel(comparison, "TZ/DZ/AZ\nvs\nTamsulosin", "TZ/DZ/AZ\nvs\n5ARI")) %>%
  ggplot(aes(x = i, y = estimate, ymin = conf.low, ymax = conf.high)) + 
  geom_point() +
  geom_linerange() +
  geom_hline(yintercept = 0, linetype = 3) +
  facet_grid(rows = vars(comparison)) + 
  labs(x = "Lead-In Duration", y = "Pearson's Correlation Coefficient") + 
  theme_bw()

ggsave("~/projects/pd-preprint/figure_SR-pr.png", width = 4, height = 4)
```